# -*- mode: ruby -*-
# vi: set ft=ruby :
servers = {
  "ServerA" => { :ip => "192.168.56.2", :cpus => 1, :mem => 1024 },
  "ServerB" => { :ip => "192.168.56.3", :cpus => 1, :mem => 1024 }
}
Vagrant.configure("2") do |config|
  servers.each_with_index do |(hostname, info), index|
     config.vm.define hostname do |cfg|
       cfg.vm.provider :virtualbox do |vb, override| 
         config.vm.box = "generic/centos7"
         override.vm.network "private_network", ip: "#{info[:ip]}"
         override.vm.hostname = hostname
         override.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/home/vagrant/.ssh/public_key"
         override.vm.provision "shell", inline: "cat /home/vagrant/.ssh/public_key >> /home/vagrant/.ssh/authorized_keys"
         override.vm.provision "shell", inline: "rm /home/vagrant/.ssh/public_key"
         vb.name = hostname
       end
     end
  end
end
