---
# Dependencies install
- hosts: mirrorClient
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Insert entry to hosts file for testing
      lineinfile:
        path: /etc/hosts
        line: "{{ ip_mirror }} icesi.mirror.edu.co"
    - name: Copy icesi repo configuration
      copy: 
        src: ../templates/repo/icesi.repo
        dest: /etc/yum.repos.d/icesi.repo
        remote_src: no
    - name: Run createrepo command
      shell: yum repolist
    - name: Clean all repos cache
      shell: yum clean all
    - name: Refresh icesi.repo
      yum:
        name: '*'
        enablerepo: 'icesirepo'
        disablerepo: '*'
        state: latest
    - name: List packages and register result to print with debug later.
      yum:
        list: available
        enablerepo: 'icesirepo'
        disablerepo: '*'
      register: result
    - name: Install packages with multiple repos disabled
      yum:
        name: 
          - python36
          - python36-pip
          - git
        enablerepo: 'icesirepo'
        disablerepo: '*'

# Repository download
- hosts: mirrorClient
  become: yes
  become_user: vagrant
  tasks:
    - git:
        repo: https://github.com/ICESI/so-microservices-python.git
        dest: /tmp/so-microservices-python
