# -*- mode: ruby -*-
# vi: set ft=ruby :
servers = {
  "mirror" => { :ip_private => 192.168.56.2,
                :ip_bridge => "192.168.131.2",
                :cpus => 1,
                :mem => 1024 },
  "client" => { :ip_private => 192.168.56.3, 
                :ip_bridge => "192.168.131.3", 
                :cpus => 1, 
                :mem => 1024 }
}
Vagrant.configure("2") do |config|
  servers.each_with_index do |(hostname, info), index|
     config.vm.define hostname do |cfg|
       cfg.vm.provider :virtualbox do |vb, override| 
         config.vm.box = "centos/7"
         override.vm.network "private_network", ip: "#{info[:ip_private]}"
         override.vm.network "public_network", bridge: "en0", ip: "#{info[:ip_bridge]}", netmask: "255.255.255.0"
         override.vm.hostname = hostname
         override.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/home/vagrant/.ssh/public_key"
         override.vm.provision "shell", inline: "cat /home/vagrant/.ssh/public_key >> /home/vagrant/.ssh/authorized_keys"
         override.vm.provision "shell", inline: "rm /home/vagrant/.ssh/public_key"
         vb.name = hostname
       end
     end
  end
end
